### GET all users

GET http://localhost:3001/api/users HTTP/1.1

### GET users without logged User

GET http://localhost:3001/api/friends/Hendrik HTTP/1.1

### Login a user
POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "Hendrik",
    "password": "neuefische"
}

### GET popular series

GET http://localhost:3001/api/popular HTTP/1.1

### SEARCH series

GET http://localhost:3001/api/search/:name HTTP/1.1

### GET Details

GET http://localhost:3001/api/detail HTTP/1.1



### POST series to Watchlist

POST http://localhost:3001/api/watchlist HTTP/1.1
Content-Type: application/json

{
    "name": "Squid Game"
}

### PATCH a new series set to a user
PATCH http://localhost:3001/api/users/Hendrik HTTP/1.1
Content-Type: application/json


{
    "vote_average": 7,
    "poster_path": "test"
}

### Delete a series from watchlist
PUT http://localhost:3000/api/users/Hendrik HTTP/1.1
Content-Type: application/json

{
    "poster_path": "test"
}

### Get logged in user
GET http://localhost:3000/api/me HTTP/1.1


### GET a single user

GET http://localhost:3000/api/users/Hendrik HTTP/1.1